---

- name: Unexpected OS
  fail: msg="OS Family {{ ansible_os_family }} {{ ansible_architecture }} is not supported"
  when: not ansible_os_family == "RedHat"

- name: Run Preliminary tasks to run tests
  include: prelim.yml
  when: (ansible_os_family == "RedHat" or ansible_os_family == "Centos")
  tags:
    - section1
    - section2
    - section3
    - section4
    - section5
    - section6
    - section7
    - section8
    - section9

- name: Run Section 01
  include: section_01.yml
  when: (ansible_os_family == "RedHat" or ansible_os_family == "Centos")
  tags: section1

- name: Run Section 02
  include: section_02.yml
  when: (ansible_os_family == "RedHat" or ansible_os_family == "Centos")
  tags: section2

- name: Run Section 03
  include: section_03.yml
  when: (ansible_os_family == "RedHat" or ansible_os_family == "Centos")
  tags: section3

- name: Run Section 04
  include: section_04.yml
  when: (ansible_os_family == "RedHat" or ansible_os_family == "Centos")
  tags: section4

- name: Run Section 05
  include: section_05.yml
  when: (ansible_os_family == "RedHat" or ansible_os_family == "Centos")
  tags: section5

- name: Run Section 06
  include: section_06.yml
  when: (ansible_os_family == "RedHat" or ansible_os_family == "Centos")
  tags: section6

- name: Run Section 07
  include: section_07.yml
  when: (ansible_os_family == "RedHat" or ansible_os_family == "Centos")
  tags: section7

- name: Run Section 08
  include: section_08.yml
  when: (ansible_os_family == "RedHat" or ansible_os_family == "Centos")
  tags: section8

- name: Run Section 09
  include: section_09.yml
  when: (ansible_os_family == "RedHat" or ansible_os_family == "Centos")
  tags: section9
