---

- name: 9.1.1 Verify system file permissions exclude list
  set_fact:
    cis_9_1_1_exclude_list_default:
      - .M.......    /etc/cron.daily
      - .M.......    /etc/cron.hourly
      - .M.......    /etc/cron.d
      - missing   c /etc/cron.deny
      - missing     /var/run/wpa_supplicant
      - .M.......    /etc/cron.daily
      - .M.......    /etc/cron.hourly
      - .M.......    /etc/cron.monthly
      - .M.......    /etc/cron.weekly
      - .M.......  c /etc/crontab
      - .M.......  c /etc/pam.d/password-auth
      - .M.......  c /etc/pam.d/system-auth
      - missing   c /etc/at.deny
    tags:
      - notscored
      - section9.1
      - section9.1.1

- name: 9.1.1 Verify system file permissions exclude list
  set_fact:
    cis_9_1_1_exclude_list_hybris:
      - .M.......    /opt
      - .M.......    /usr/local
      - missing   c /etc/httpd/conf.d/welcome.conf
      - missing   c /etc/httpd/conf.d/ssl.conf
      - .M...UG..    /usr/lib/node_modules/inherits
      - .M.......    /var/lib/nfs/rpc_pipefs
    tags:
      - notscored
      - section9.1
      - section9.1.1

- name: 9.1.1 Verify system file permissions (Not Scored)
  command: rpm -Va --nomtime --nosize --nomd5 --nolinkto
  register: cis_9_1_1_output
  #the command automatically gives an RC of 1
  failed_when: cis_9_1_1_output.rc != 0 and cis_9_1_1_output.rc != 1
  changed_when: false
  become: True
  become_user: root
  tags:
    - notscored
    - section9.1
    - section9.1.1

- name: 9.1.1 Verify system file permissions error
  fail: "{{ item }} is not in the exclude list"
  when: item not in cis_9_1_1_exclude_list_default and item not in cis_9_1_1_exclude_list_hybris
  with_items: cis_9_1_1_output.stdout_lines
  tags:
    - notscored
    - section9.1
    - section9.1.1
