---

- name: 4.1.1 Disable IP Forwarding (Scored)
  sysctl: sysctl_file=/usr/lib/sysctl.d/10-cis.conf name=net.ipv4.ip_forward value=0 state=present reload=yes
  become: true
  become_user: root
  tags:
    - scored
    - section4.1
    - section4.1.1

- name: 4.1.2 Disable Send Packet Redirects (Scored)
  sysctl: name=net.ipv4.conf.all.send_redirects value=0 state=present ignoreerrors=true
  become: true
  become_user: root
  tags:
    - scored
    - section4.1
    - section4.1.2

- name: 4.1.2 Disable Send Packet Redirects (Scored)
  sysctl: name=net.ipv4.conf.default.send_redirect value=0 state=present ignoreerrors=true
  become: true
  become_user: root
  tags:
    - scored
    - section4.1
    - section4.1.2

- name: 4.2.1 Disable Source Routed Packet Acceptance (Scored)
  sysctl: name=net.ipv4.conf.all.accept_source_route value=0 state=present ignoreerrors=true
  become: true
  become_user: root
  tags:
    - scored
    - section4.2
    - section4.2.1

- name: 4.2.1 Disable Source Routed Packet Acceptance (Scored)
  sysctl: name=net.ipv4.conf.default.accept_source_route value=0 state=present ignoreerrors=true
  become: true
  become_user: root
  tags:
    - scored
    - section4.2
    - section4.2.1

- name: 4.2.2 Disable ICMP Redirect Acceptance (Scored)
  sysctl: name=net.ipv4.conf.all.accept_redirects value=0 state=present ignoreerrors=true
  become: true
  become_user: root
  tags:
    - scored
    - section4.2
    - section4.2.2

- name: 4.2.2 Disable ICMP Redirect Acceptance (Scored)
  sysctl: name=net.ipv4.conf.default.accept_redirects value=0 state=present ignoreerrors=true
  become: true
  become_user: root
  tags:
    - scored
    - section4.2
    - section4.2.2

- name: 4.2.4 Log Suspicious Packets (Scored)
  sysctl: name=net.ipv4.conf.all.log_martians value=1 state=present ignoreerrors=true
  become: true
  become_user: root
  tags:
    - scored
    - section4.2
    - section4.2.4

- name: 4.2.4 Log Suspicious Packets (Scored)
  sysctl: name=net.ipv4.conf.default.log_martians value=1 state=present ignoreerrors=true
  become: true
  become_user: root
  tags:
    - scored
    - section4.2
    - section4.2.4

- name: 4.2.5 Enable Ignore Broadcast Requests (Scored)
  sysctl: name=net.ipv4.icmp_echo_ignore_broadcasts value=1 state=present ignoreerrors=true
  become: true
  become_user: root
  tags:
    - scored
    - section4.2
    - section4.2.5

- name: 4.2.6 Enable Bad Error Message Protection (Scored)
  sysctl: name=net.ipv4.icmp_ignore_bogus_error_responses value=1 state=present ignoreerrors=true
  become: true
  become_user: root
  tags:
    - scored
    - section4.2
    - section4.2.6

- name: 4.2.8 Enable TCP SYN Cookies (Scored)
  sysctl: name=net.ipv4.tcp_syncookies value=1 state=present ignoreerrors=true
  become: true
  become_user: root
  tags:
    - scored
    - section4.2
    - section4.2.8

- name: 4.4.1.1 Disable IPv6 Router Advertisements (Not Scored)
  sysctl: name=net.ipv6.conf.all.accept_ra value=0 state=present ignoreerrors=true
  become: true
  become_user: root
  tags:
    - notscored
    - section4.4
    - section4.4.1
    - section4.4.1.1

- name: 4.4.1.1 Disable IPv6 Router Advertisements (Not Scored)
  sysctl: name=net.ipv6.conf.default.accept_ra value=0 state=present ignoreerrors=true
  become: true
  become_user: root
  tags:
    - notscored
    - section4.4
    - section4.4.1
    - section4.4.1.1

- name: 4.4.1.2 Disable IPv6 Redirect Acceptance (Not Scored)
  sysctl: name=net.ipv6.conf.all.accept_redirects value=0 state=present ignoreerrors=true
  become: true
  become_user: root
  tags:
    - notscored
    - section4.4
    - section4.4.1
    - section4.4.1.2

- name: 4.4.1.2 Disable IPv6 Redirect Acceptance (Not Scored)
  sysctl: name=net.ipv6.conf.default.accept_redirects value=0 state=present ignoreerrors=true
  become: true
  become_user: root
  tags:
    - notscored
    - section4.4
    - section4.4.1
    - section4.4.1.2

- name: 4.4.2 Disable IPv6 (disable in network config) (Not Scored)
  lineinfile: state=present dest=/etc/sysconfig/network regexp=^NETWORKING_IPV6 line=NETWORKING_IPV6=no
  become: true
  become_user: root
  tags:
    - notscored
    - section4.4
    - section4.4.2

- name: 4.4.2 Disable IPv6 (disable in network config) (Not Scored)
  lineinfile: state=present dest=/etc/sysconfig/network regexp=^IPV6INIT line=IPV6INIT=no
  become: true
  become_user: root
  tags:
    - notscored
    - section4.4
    - section4.4.2

- name: 4.4.2 Disable IPv6 (disable via modprobe) (Not Scored)
  lineinfile: state=present create=yes dest=/etc/modprobe.d/ipv6.conf line="options ipv6 disable=1"
  become: true
  become_user: root
  tags:
    - notscored
    - section4.4
    - section4.4.2

- name: 4.4.2 Disable IPv6 (disable ip6tables) (Not Scored)
  service: name=ip6tables enabled=no state=stopped
  become: true
  become_user: root
  tags:
    - notscored
    - section4.4
    - section4.4.2

- name: 4.4.2 Disable IPv6 (flush routes) (Not Scored)
  command: /sbin/sysctl -w net.ipv6.route.flush=1
  changed_when: false
  become: true
  become_user: root
  tags:
    - notscored
    - section4.4
    - section4.4.2

- name: 4.5.1 Install TCP Wrappers (Not Scored)
  yum: name=tcp_wrappers state=installed
  become: true
  become_user: root
  tags:
    - notscored
    - section4.5
    - section4.5.1

- name: 4.5.2 Create /etc/hosts.allow (Not Scored)
  lineinfile: state=present create=yes dest=/etc/hosts.allow regexp=^ALL line=ALL:{{ tcp_allow | default("ALL") }}
  become: true
  become_user: root
  tags:
    - notscored
    - section4.5
    - section4.5.2

- name: 4.5.3 Verify Permissions on /etc/hosts.allow (Scored)
  file: path=/etc/hosts.allow mode=0644
  become: true
  become_user: root
  tags:
    - scored
    - section4.5
    - section4.5.3

- name: 4.5.4 Create /etc/hosts.deny (Not Scored)
  lineinfile: state=present create=yes dest=/etc/hosts.deny line=ALL:ALL
  become: true
  become_user: root
  tags:
    - notscored
    - section4.5
    - section4.5.4

- name: 4.5.5 Verify Permissions on /etc/hosts.deny (Scored)
  file: path=/etc/hosts.deny mode=0644
  become: true
  become_user: root
  tags:
    - scored
    - section4.5
    - section4.5.5

- name: 4.6.1 Disable DCCP (Not Scored)
  lineinfile: state=present create=yes dest=/etc/modprobe.d/CIS.conf line="install dccp /bin/true"
  become: true
  become_user: root
  tags:
    - notscored
    - section4.6
    - section4.6.1

- name: 4.6.2 Disable SCTP (Not Scored)
  lineinfile: state=present create=yes dest=/etc/modprobe.d/CIS.conf line="install sctp /bin/true"
  become: true
  become_user: root
  tags:
    - notscored
    - section4.6
    - section4.6.2

- name: 4.6.3 Disable RDS (Not Scored)
  lineinfile: state=present create=yes dest=/etc/modprobe.d/CIS.conf line="install rds /bin/true"
  become: true
  become_user: root
  tags:
    - notscored
    - section4.6
    - section4.6.3

- name: 4.6.4 Disable TIPC (Not Scored)
  lineinfile: state=present create=yes dest=/etc/modprobe.d/CIS.conf line="install tipc /bin/true"
  become: true
  become_user: root
  tags:
    - notscored
    - section4.6
    - section4.6.4

- name: 4.7 - 4.8 Determine if IPTables is used.
  shell: rpm -qa | grep iptables-services
  failed_when: cis_iptables_result.rc != 0 and cis_iptables_result.rc != 1
  register: cis_iptables_result
  become: true
  become_user: root
  changed_when: false
  tags:
    - scored
    - section4
    - section4.7
    - section4.8

- name: 4.7 Enable IPtables (Scored)
  service: name=iptables enabled=yes state=started
  when: cis_iptables_result.stdout_lines.0 is defined
  tags:
    - scored
    - section4.7

- name: 4.8 Enable IP6tables (Not Scored)
  service: name=ip6tables enabled=yes state=started
  when: cis_iptables_result.stdout_lines.0 is defined
  tags:
    - notscored
    - section4.8
