---

- name: 1.1.18 - 1.1.24 Create /etc/modprobe.d/CIS.conf with root ownership & mode
  file: path=/etc/modprobe.d/CIS.conf state=touch owner=root group=root mode=0600
  changed_when: false
  become: true
  become_user: root
  tags:
    - notscored
    - section1.1
    - section1.1.18
    - section1.1.19
    - section1.1.20
    - section1.1.21
    - section1.1.22
    - section1.1.23
    - section1.1.24

- name: 1.1.18 Disable Mounting of cramfs Filesystems (Not Scored)
  lineinfile: state=present dest=/etc/modprobe.d/CIS.conf line="install cramfs /bin/true"
  become: true
  become_user: root
  tags:
    - notscored
    - section1.1
    - section1.1.18

- name: 1.1.19 Disable Mounting of freevxfs Filesystems (Not Scored)
  lineinfile: state=present dest=/etc/modprobe.d/CIS.conf line="install freevxfs /bin/true"
  become: True
  become_user: root
  tags:
    - notscored
    - section1.1
    - section1.1.19

- name: 1.1.20 Disable Mounting of jffs2 Filesystems (Not Scored)
  lineinfile: state=present dest=/etc/modprobe.d/CIS.conf line="install jffs2 /bin/true"
  become: true
  become_user: root
  tags:
    - notscored
    - section1.1
    - section1.1.20

- name: 1.1.21 Disable Mounting of hfs Filesystems (Not Scored)
  lineinfile: state=present dest=/etc/modprobe.d/CIS.conf line="install hfs /bin/true"
  become: true
  become_user: root
  tags:
    - notscored
    - section1.1
    - section1.1.21

- name: 1.1.22 Disable Mounting of hfsplus Filesystems (Not Scored)
  lineinfile: state=present dest=/etc/modprobe.d/CIS.conf line="install hfsplus /bin/true"
  become: true
  become_user: root
  tags:
    - notscored
    - section1.1
    - section1.1.22

- name: 1.1.23 Disable Mounting of squashfs Filesystems (Not Scored)
  lineinfile: state=present dest=/etc/modprobe.d/CIS.conf line="install squashfs /bin/true"
  become: true
  become_user: root
  tags:
    - notscored
    - section1.1
    - section1.1.23

- name: 1.1.24 Disable Mounting of udf Filesystems (Not Scored)
  lineinfile: state=present dest=/etc/modprobe.d/CIS.conf line="install udf /bin/true"
  become: true
  become_user: root
  tags:
    - notscored
    - section1.1
    - section1.1.24

- name: 1.2.4 Check to see if rhnsd daemon is installed (Not Scored)
  stat: path=/etc/init.d/rhnsd
  register: rhnsd_service
  when: ansible_distribution == "RedHat"
  tags:
    - notscored
    - section1.2
    - section1.2.4

- name: 1.2.4 Disable the rhnsd Daemon (Not Scored)
  command: /sbin/chkconfig rhnsd off
  when: not (ansible_virtualization_type == 'virtualbox' and ansible_virtualization_role == 'guest')
  tags:
    - notscored
    - section1.2
    - section1.2.4

- name: 1.3.1 Install AIDE (Scored)
  yum: name=aide state=latest
  always_run: true
  become: true
  become_user: root
  tags:
    - scored
    - section1.3
    - section1.3.1

- name: 1.3.1 Install AIDE (Initialize AIDE) (Scored)
  command: /usr/sbin/aide --init -B 'database_out=file:/var/lib/aide/aide.db.gz' creates=/var/lib/aide/aide.db.gz
  become: true
  become_user: root
  tags:
    - scored
    - section1.3
    - section1.3.1

- name: 1.3.1 Install AIDE (check is prelink installed) (Scored)
  stat: path=/usr/sbin/prelink
  register: prelink_stat
  tags:
    - scored
    - section1.3
    - section1.3.1

- name: 1.3.1 Install AIDE (Disable Prelinking) (Scored)
  lineinfile: state=present dest=/etc/sysconfig/prelink regexp=^PRELINKING= line=PRELINKING=no create=yes
  when: prelink_stat.stat.exists
  tags:
    - scored
    - section1.3
    - section1.3.1

- name: 1.3.2 Implement Periodic Execution of File Integrity (Scored)
  cron: name="Run AIDE (CIS 1.3.2)" minute="0" hour="5" job="/usr/sbin/aide --check"
  become: true
  become_user: root
  tags:
    - scored
    - section1.3
    - section1.3.2

- name: 1.4.1 Enable SELinux in /etc/grub.conf (Scored)
  lineinfile: state=absent dest=/etc/grub.conf line="selinux=0"
  tags:
    - scored
    - section1.4
    - section1.4.1

- name: 1.4.1 Enable SELinux in /etc/grub.conf (Scored)
  lineinfile: state=absent dest=/etc/grub.conf line="enforcing=0"
  tags:
    - scored
    - section1.4
    - section1.4.1

- name: 1.4.2 Set the SELinux State (Scored)
  yum: name=selinux-policy-targeted state=latest
  always_run: true
  tags:
    - scored
    - section1.4
    - section1.4.2

- name: 1.4.3 Set the SELinux Policy (Scored)
  selinux: state=enforcing policy=targeted
  tags:
    - scored
    - section1.4
    - section1.4.3

- name: 1.4.4 Remove SETroubleshoot (Scored)
  yum: name=setroubleshoot state=absent
  tags:
    - scored
    - section1.4
    - section1.4.4

- name: 1.4.5 Remove MCS Translation Service (mcstrans) (Scored)
  yum: name=mcstrans state=absent
  tags:
    - scored
    - section1.4
    - section1.4.5

- name: 1.4.6 Check for unconfined daemons (Scored)
  shell: ps -eZ | egrep "initrc" | egrep -vw "tr|ps|egrep|bash|awk" | tr ':' ' ' | awk '{ print $NF }'
  register: unconfined_daemons
  changed_when: false
  failed_when: unconfined_daemons.stdout_lines.0 is defined
  tags:
    - scored
    - section1.4
    - section1.4.6
